version: "3.8"
services:
  proalgotrader_core:
    image: ghcr.io/krunaldodiya/proalgotrader_core:latest
    container_name: proalgotrader_core
    env_file:
      - .env
    command: ["./proalgotrader"]
    volumes:
      - ./project:/app/project
