version: "3.8"
services:
  proalgotrader_core:
    image: ghcr.io/krunaldodiya/proalgotrader_core:latest
    container_name: proalgotrader_core
    env_file:
      - .env
    command: ["./proalgotrader"]
    volumes:
      - ./project:/app/project
    networks:
      - proalgotrader_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  proalgotrader_network:
    driver: bridge
