version: "3.8"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proalgotrader_core_development
    env_file:
      - .env
    command: ["python", "main.py", "--environment", "development"]
    volumes:
      - ./project:/app/project

  production:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proalgotrader_core_production
    env_file:
      - .env
    command: ["python", "main.py", "--environment", "production"]
