version: "3.8"
services:
  development:
    image: ghcr.io/krunaldodiya/proalgotrader_core:latest
    container_name: proalgotrader_core_development
    env_file:
      - .env
    command: ["./proalgotrader", "--environment", "development"]
    volumes:
      - ./project:/app/project

  production:
    image: ghcr.io/krunaldodiya/proalgotrader_core:latest
    container_name: proalgotrader_core_production
    env_file:
      - .env
    command: ["./proalgotrader", "--environment", "production"]
